"""
gen_splash_art.py
-----------------
Generates the cabin bracket art for Lodge's splash screen.
Run from the project root:

    python3 scripts/gen_splash_art.py

Writes the art as a Rust const to:
    crates/runtime/src/tui/splash_art.rs

Requires: Pillow  (pip install Pillow)
Source image: assets/cabin.jpg
"""

from PIL import Image, ImageDraw, ImageEnhance
import math
import os

SRC = os.path.join(os.path.dirname(__file__), "..", "assets", "cabin.jpg")
OUT = os.path.join(os.path.dirname(__file__), "..", "crates", "runtime",
                   "src", "tui", "splash_art.rs")

W, H = 40, 21   # bracket-pairs wide × rows tall → 80 terminal cols × 21 rows

img = Image.open(SRC).convert("RGB")

# Square crop from centre
iw, ih = img.size
min_dim = min(iw, ih)
left = (iw - min_dim) // 2
top  = (ih - min_dim) // 2
img = img.crop((left, top, left + min_dim, top + min_dim))

# Boost for terminal legibility
img = ImageEnhance.Brightness(img).enhance(1.8)
img = ImageEnhance.Contrast(img).enhance(1.6)
img = ImageEnhance.Color(img).enhance(1.5)

img = img.resize((W, H), Image.LANCZOS)

RESET = "\x1b[0m"

def ansi(r, g, b):
    return f"\x1b[38;2;{r};{g};{b}m"

cx, cy = W / 2, H / 2

rows = []
for y in range(H):
    row = ""
    for x in range(W):
        dx = (x - cx + 0.5) / (W / 2)
        dy = (y - cy + 0.5) / (H / 2)
        dist = math.sqrt(dx*dx + dy*dy)

        if dist > 0.97:
            row += "  "
        else:
            r, g, b = img.getpixel((x, y))
            # Vignette
            v  = max(0.0, 1.0 - (dist * 1.05) ** 4)
            r  = min(255, int(r * v))
            g  = min(255, int(g * v))
            b  = min(255, int(b * v))

            # Bracket zone
            rel_y = y / H
            char = "{}" if rel_y < 0.35 else "()" if rel_y >= 0.72 else "[]"

            row += ansi(r, g, b) + char + RESET
    rows.append(row)

art = "\n".join(rows)

rust = f'''// AUTO-GENERATED by scripts/gen_splash_art.py — do not edit by hand.
// Source: assets/cabin.jpg
// Dimensions: {W * 2} terminal columns × {H} rows (circular crop)

pub const CABIN_ART: &str = "{art.replace(chr(92), chr(92)+chr(92)).replace('"', '\\"')}";
'''

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as f:
    f.write(rust)

print(f"Written to {OUT}")
print(f"Art dimensions: {W*2} cols × {H} rows")
